# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d827d9be558beb3a1caa58e33c7eb88aea165b831190c769a4e534a87245395d1f769071ee3688f1a969d28f50398e96fab9e423ecb11e4635bdd1ea15ee32

test:
  secret_key_base: de7a87589174c45a2d2ef8060d75b10211e4c3ec1e400bee83330b12524233e0e79599324b6af029f2b16f94a88ba5e5a6fd24134ee43bf893889d001d0860c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
